const dishes = [
  {
    categoryId: 1,
    mealType: "Starter",
    type: "VEG",
    description: "Crispy fried potato fingers tossed in spicy masala.",
    image: null,
    add: false,
    category: {
      id: 1,
      name: "North Indian",
      image:
        "https://storage.googleapis.com/chefkartimages/customer_app_assets/star_chef/north_indian.png",
      isRecommendedForMealSuggestion: true,
    },
    dishType: "SNACKS",
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    id: 1,
    name: "Masala French Fries",
    ingredients: [
      { name: "Potato", quantity: "3-4 pcs", type: "VEG" },
      { name: "Oil", quantity: "500 ml", type: "VEG" },
      { name: "Red Chili Powder", quantity: "1 tsp", type: "VEG" },
      { name: "Salt", quantity: "to taste", type: "VEG" },
    ],
  },
  {
    categoryId: 2,
    mealType: "Starter",
    type: "NON VEG",
    description:
      "Juicy chicken drumsticks marinated in spicy masala and grilled.",
    image: null,
    add: false,
    category: {
      id: 2,
      name: "Mughlai",
      image:
        "https://img.freepik.com/free-photo/top-view-delicious-indian-food-arrangement_23-2148747719.jpg",
      isRecommendedForMealSuggestion: true,
    },
    dishType: "SNACKS",
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    id: 2,
    name: "Tandoori Chicken",
    ingredients: [
      { name: "Chicken Drumsticks", quantity: "6 pcs", type: "NON VEG" },
      { name: "Yogurt", quantity: "100 gm", type: "VEG" },
      { name: "Ginger Garlic Paste", quantity: "1 tbsp", type: "VEG" },
      { name: "Red Chili Powder", quantity: "1 tsp", type: "VEG" },
      { name: "Salt", quantity: "to taste", type: "VEG" },
    ],
  },
  {
    categoryId: 1,
    mealType: "Starter",
    type: "VEG",
    description: "Paneer cubes marinated and grilled in tandoor.",
    image: null,
    add: false,
    category: {
      id: 1,
      name: "North Indian",
      image:
        "https://storage.googleapis.com/chefkartimages/customer_app_assets/star_chef/north_indian.png",
      isRecommendedForMealSuggestion: true,
    },
    dishType: "SNACKS",
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    id: 3,
    name: "Paneer Tikka",
    ingredients: [
      { name: "Paneer", quantity: "200 gm", type: "VEG" },
      { name: "Yogurt", quantity: "50 gm", type: "VEG" },
      { name: "Capsicum", quantity: "1 pc", type: "VEG" },
      { name: "Onion", quantity: "1 pc", type: "VEG" },
      { name: "Spices", quantity: "1 tsp", type: "VEG" },
    ],
  },
  {
    categoryId: 3,
    mealType: "Starter",
    type: "NON VEG",
    description: "Crispy fried prawns served with chutney.",
    image: null,
    add: false,
    category: {
      id: 3,
      name: "Seafood",
      image:
        "https://img.freepik.com/free-photo/fried-prawns-served-with-lemon_140725-4070.jpg",
      isRecommendedForMealSuggestion: true,
    },
    dishType: "SNACKS",
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    id: 4,
    name: "Crispy Prawns",
    ingredients: [
      { name: "Prawns", quantity: "250 gm", type: "NON VEG" },
      { name: "Cornflour", quantity: "2 tbsp", type: "VEG" },
      { name: "Oil", quantity: "200 ml", type: "VEG" },
      { name: "Chili Powder", quantity: "1 tsp", type: "VEG" },
      { name: "Salt", quantity: "to taste", type: "VEG" },
    ],
  },
  {
    categoryId: 4,
    mealType: "Starter",
    type: "VEG",
    description: "Golden fried crispy samosas stuffed with spiced potatoes.",
    image: null,
    add: false,
    category: {
      id: 4,
      name: "Snacks",
      image:
        "https://static.toiimg.com/thumb/61050397.cms?width=1200&height=900",
      isRecommendedForMealSuggestion: true,
    },
    dishType: "SNACKS",
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    id: 5,
    name: "Samosa",
    ingredients: [
      { name: "Maida", quantity: "1 cup", type: "VEG" },
      { name: "Potatoes", quantity: "2 pcs", type: "VEG" },
      { name: "Oil", quantity: "200 ml", type: "VEG" },
      { name: "Spices", quantity: "1 tsp", type: "VEG" },
    ],
  },
  {
    categoryId: 4,
    mealType: "Starter",
    type: "VEG",
    description: "Fried spinach fritters served with green chutney.",
    image: null,
    add: false,
    category: {
      id: 4,
      name: "Snacks",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaDNDfwnyXH6fdcfWo4bG4JAjDn51_sNmdXA&s",
      isRecommendedForMealSuggestion: true,
    },
    dishType: "SNACKS",
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    id: 6,
    name: "Palak Pakora",
    ingredients: [
      { name: "Spinach", quantity: "1 cup", type: "VEG" },
      { name: "Chickpea Flour", quantity: "1/2 cup", type: "VEG" },
      { name: "Oil", quantity: "200 ml", type: "VEG" },
      { name: "Spices", quantity: "1 tsp", type: "VEG" },
    ],
  },

  {
    categoryId: 2,
    mealType: "Main Course",
    type: "NON VEG",
    description: "Creamy butter chicken cooked in tomato gravy.",
    image: null,
    add: false,
    category: {
      id: 2,
      name: "Mughlai",
      image:
        "https://img.freepik.com/free-photo/top-view-delicious-indian-food-arrangement_23-2148747719.jpg",
      isRecommendedForMealSuggestion: true,
    },
    dishType: "CURRY",
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    id: 7,
    name: "Butter Chicken",
    ingredients: [
      { name: "Chicken", quantity: "500 gm", type: "NON VEG" },
      { name: "Butter", quantity: "50 gm", type: "VEG" },
      { name: "Tomato Puree", quantity: "100 gm", type: "VEG" },
      { name: "Cream", quantity: "50 ml", type: "VEG" },
      { name: "Spices", quantity: "1 tsp", type: "VEG" },
    ],
  },
  {
    categoryId: 2,
    mealType: "Main Course",
    type: "NON VEG",
    description: "Mutton cooked in spicy Kashmiri-style gravy.",
    image: null,
    add: false,
    category: {
      id: 2,
      name: "Mughlai",
      image:
        "https://img.freepik.com/free-photo/top-view-delicious-indian-food-arrangement_23-2148747719.jpg",
      isRecommendedForMealSuggestion: true,
    },
    dishType: "CURRY",
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    id: 8,
    name: "Mutton Rogan Josh",
    ingredients: [
      { name: "Mutton", quantity: "500 gm", type: "NON VEG" },
      { name: "Yogurt", quantity: "50 gm", type: "VEG" },
      { name: "Onion", quantity: "1 pc", type: "VEG" },
      { name: "Tomato Puree", quantity: "50 gm", type: "VEG" },
      { name: "Spices", quantity: "1 tsp", type: "VEG" },
    ],
  },
  {
    categoryId: 1,
    mealType: "Main Course",
    type: "VEG",
    description:
      "Paneer cubes in spicy onion gravy with onions and capsicum cubes.",
    image: null,
    add: false,
    category: {
      id: 1,
      name: "North Indian",
      image:
        "https://storage.googleapis.com/chefkartimages/customer_app_assets/star_chef/north_indian.png",
      isRecommendedForMealSuggestion: true,
    },
    dishType: "CURRY",
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    id: 9,
    name: "Kadhai Paneer",
    ingredients: [
      { name: "Paneer", quantity: "200 gm", type: "VEG" },
      { name: "Onion", quantity: "1 pc", type: "VEG" },
      { name: "Capsicum", quantity: "1 pc", type: "VEG" },
      { name: "Spices", quantity: "1 tsp", type: "VEG" },
      { name: "Oil", quantity: "50 ml", type: "VEG" },
    ],
  },
  {
    categoryId: 1,
    mealType: "Main Course",
    type: "VEG",
    description: "Chickpeas cooked in Punjabi-style masala gravy.",
    image: null,
    add: false,
    category: {
      id: 1,
      name: "North Indian",
      image:
        "https://storage.googleapis.com/chefkartimages/customer_app_assets/star_chef/north_indian.png",
      isRecommendedForMealSuggestion: true,
    },
    dishType: "CURRY",
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    id: 10,
    name: "Chole Masala",
    ingredients: [
      { name: "Chickpeas", quantity: "200 gm", type: "VEG" },
      { name: "Onion", quantity: "1 pc", type: "VEG" },
      { name: "Tomato", quantity: "1 pc", type: "VEG" },
      { name: "Spices", quantity: "1 tsp", type: "VEG" },
      { name: "Oil", quantity: "50 ml", type: "VEG" },
    ],
  },
  {
    categoryId: 5,
    mealType: "Main Course",
    type: "VEG",
    description: "Slow cooked Dal Makhani with butter and cream.",
    image: null,
    add: false,
    category: {
      id: 5,
      name: "Punjabi",
      image:
        "https://img.freepik.com/free-photo/dal-makhani-served-bowl_57665-3036.jpg",
      isRecommendedForMealSuggestion: true,
    },
    dishType: "CURRY",
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    id: 11,
    name: "Dal Makhani",
    ingredients: [
      { name: "Black Lentils", quantity: "200 gm", type: "VEG" },
      { name: "Butter", quantity: "50 gm", type: "VEG" },
      { name: "Cream", quantity: "50 ml", type: "VEG" },
      { name: "Spices", quantity: "1 tsp", type: "VEG" },
      { name: "Oil", quantity: "50 ml", type: "VEG" },
    ],
  },
  {
    categoryId: 5,
    mealType: "Main Course",
    type: "VEG",
    description: "Mixed seasonal vegetables cooked in spicy gravy.",
    image: null,
    add: false,
    category: {
      id: 5,
      name: "Punjabi",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTS4krno8WamnlgtHxFtLo3myxzjobq7xWdPw&s",
      isRecommendedForMealSuggestion: true,
    },
    dishType: "CURRY",
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    id: 12,
    name: "Mix Veg Curry",
    ingredients: [
      { name: "Carrot", quantity: "1 pc", type: "VEG" },
      { name: "Beans", quantity: "50 gm", type: "VEG" },
      { name: "Cauliflower", quantity: "50 gm", type: "VEG" },
      { name: "Capsicum", quantity: "1 pc", type: "VEG" },
      { name: "Spices", quantity: "1 tsp", type: "VEG" },
    ],
  },
  {
    categoryId: 6,
    mealType: "Main Course",
    type: "NON VEG",
    description: "Biryani rice cooked with chicken & spices.",
    image: null,
    add: false,
    category: {
      id: 6,
      name: "Hyderabadi",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPcdlgGqTXb-qtbAK_WgscTy2TimgPjzn9fw&s",
      isRecommendedForMealSuggestion: true,
    },
    dishType: "RICE",
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    id: 13,
    name: "Chicken Biryani",
    ingredients: [
      { name: "Basmati Rice", quantity: "200 gm", type: "VEG" },
      { name: "Chicken", quantity: "250 gm", type: "NON VEG" },
      { name: "Spices", quantity: "2 tsp", type: "VEG" },
      { name: "Onion", quantity: "1 pc", type: "VEG" },
      { name: "Oil", quantity: "50 ml", type: "VEG" },
    ],
  },
  {
    categoryId: 6,
    mealType: "Main Course",
    type: "VEG",
    description: "Biryani rice cooked with vegetables & spices.",
    image: null,
    add: false,
    category: {
      id: 6,
      name: "Hyderabadi",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTa7wtzC0xvsruRVViH0Gece8SOuoNC7FInuw&s",
      isRecommendedForMealSuggestion: true,
    },
    dishType: "RICE",
    forChefit: true,
    forParty: true,
    nameHi: "",
    nameBn: "",
    id: 14,
    name: "Veg Biryani",
    ingredients: [
      { name: "Basmati Rice", quantity: "200 gm", type: "VEG" },
      { name: "Carrot", quantity: "50 gm", type: "VEG" },
      { name: "Beans", quantity: "50 gm", type: "VEG" },
      { name: "Cauliflower", quantity: "50 gm", type: "VEG" },
      { name: "Spices", quantity: "2 tsp", type: "VEG" },
    ],
  },

  {
    categoryId: 7,
    mealType: "Dessert",
    type: "VEG",
    description: "Deep fried milk dumplings soaked in sugar syrup.",
    add: false,
    image:
      "https://i0.wp.com/www.chitrasfoodbook.com/wp-content/uploads/2016/10/gulab-jamun-using-mix.jpg?w=1200&ssl=1",
    category: { id: 7, name: "Desserts" },
    dishType: "SWEET",
    forChefit: true,
    forParty: true,
    id: 15,
    name: "Gulab Jamun",
    ingredients: [
      { name: "Milk Powder", quantity: "100 gm", type: "VEG" },
      { name: "Flour", quantity: "20 gm", type: "VEG" },
      { name: "Sugar", quantity: "200 gm", type: "VEG" },
      { name: "Ghee", quantity: "50 ml", type: "VEG" },
    ],
  },
  {
    categoryId: 7,
    mealType: "Dessert",
    type: "VEG",
    description: "Sweet spiral-shaped fried batter soaked in sugar syrup.",
    image: "https://static.toiimg.com/thumb/61050397.cms?width=1200&height=900",
    add: false,
    category: { id: 7, name: "Desserts" },
    dishType: "SWEET",
    forChefit: true,
    forParty: true,
    id: 16,
    name: "Jalebi",
    ingredients: [
      { name: "Maida", quantity: "100 gm", type: "VEG" },
      { name: "Sugar", quantity: "150 gm", type: "VEG" },
      { name: "Oil", quantity: "200 ml", type: "VEG" },
      { name: "Saffron", quantity: "few strands", type: "VEG" },
    ],
  },
  {
    categoryId: 7,
    mealType: "Dessert",
    type: "VEG",
    description: "Soft spongy balls made from chhena in sweet syrup.",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSob3EerZuChoGLlNXmz5-YZSC4-W-fmFxXSA&s",
    add: false,
    category: { id: 7, name: "Desserts" },
    dishType: "SWEET",
    forChefit: true,
    forParty: true,
    id: 17,
    name: "Rasgulla",
    ingredients: [
      { name: "Chhena", quantity: "200 gm", type: "VEG" },
      { name: "Sugar", quantity: "200 gm", type: "VEG" },
      { name: "Water", quantity: "200 ml", type: "VEG" },
    ],
  },
  {
    categoryId: 7,
    mealType: "Dessert",
    type: "VEG",
    description: "Rice flour and jaggery dumplings steamed to perfection.",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoskr6VEQBuFZyo8e9UQGYzBtOMrflLFeZrg&s",
    add: false,
    category: { id: 7, name: "Desserts" },
    dishType: "SWEET",
    forChefit: true,
    forParty: true,
    id: 18,
    name: "Modak",
    ingredients: [
      { name: "Rice Flour", quantity: "100 gm", type: "VEG" },
      { name: "Jaggery", quantity: "50 gm", type: "VEG" },
      { name: "Coconut", quantity: "50 gm", type: "VEG" },
    ],
  },

  {
    categoryId: 8,
    mealType: "Sides",
    type: "VEG",
    description: "Fresh cucumber and yogurt side dish with spices.",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtbjdA6-9lIafF_S0yRoETeT64sfNBo0VHNA&s",
    add: false,
    category: { id: 8, name: "Sides" },
    dishType: "ACCOMPANIMENT",
    forChefit: true,
    forParty: true,
    id: 19,
    name: "Cucumber Raita",
    ingredients: [
      { name: "Cucumber", quantity: "1 pc", type: "VEG" },
      { name: "Yogurt", quantity: "100 gm", type: "VEG" },
      { name: "Salt", quantity: "to taste", type: "VEG" },
      { name: "Cumin Powder", quantity: "1 tsp", type: "VEG" },
    ],
  },
  {
    categoryId: 8,
    mealType: "Sides",
    type: "VEG",
    description: "Mix of fresh vegetables seasoned with lemon and salt.",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsE8_SUC8DgFeqGGKmTrcMNNJPiFlem4h5Vg&s",
    add: false,
    category: { id: 8, name: "Sides" },
    dishType: "ACCOMPANIMENT",
    forChefit: true,
    forParty: true,
    id: 20,
    name: "Vegetable Salad",
    ingredients: [
      { name: "Cucumber", quantity: "1 pc", type: "VEG" },
      { name: "Tomato", quantity: "1 pc", type: "VEG" },
      { name: "Carrot", quantity: "1 pc", type: "VEG" },
      { name: "Lemon Juice", quantity: "1 tsp", type: "VEG" },
      { name: "Salt", quantity: "to taste", type: "VEG" },
    ],
  },
  {
    categoryId: 8,
    mealType: "Sides",
    type: "VEG",
    description: "Pickled vegetables with tangy spices for a side dish.",
    image: "https://5.imimg.com/data5/EE/OC/MY-7355655/mixed-pickle.jpg",
    add: false,
    category: { id: 8, name: "Sides" },
    dishType: "ACCOMPANIMENT",
    forChefit: true,
    forParty: true,
    id: 21,
    name: "Mixed Vegetable Pickle",
    ingredients: [
      { name: "Carrot", quantity: "50 gm", type: "VEG" },
      { name: "Turnip", quantity: "50 gm", type: "VEG" },
      { name: "Chili Powder", quantity: "1 tsp", type: "VEG" },
      { name: "Mustard Seeds", quantity: "1 tsp", type: "VEG" },
      { name: "Oil", quantity: "50 ml", type: "VEG" },
    ],
  },
  {
    categoryId: 8,
    mealType: "Sides",
    type: "VEG",
    description: "Soft butter naan cooked in tandoor.",
    image:
      "https://t3.ftcdn.net/jpg/13/76/13/86/360_F_1376138644_y7ciRIG77EWcaPKWXD1iWQR2SpR2ACSW.jpg",
    add: false,
    category: { id: 8, name: "Sides" },
    dishType: "ACCOMPANIMENT",
    forChefit: true,
    forParty: true,
    id: 22,
    name: "Butter Naan",
    ingredients: [
      { name: "All Purpose Flour", quantity: "200 gm", type: "VEG" },
      { name: "Yeast", quantity: "1 tsp", type: "VEG" },
      { name: "Milk", quantity: "50 ml", type: "VEG" },
      { name: "Butter", quantity: "20 gm", type: "VEG" },
    ],
  },
  {
    categoryId: 8,
    mealType: "Sides",
    type: "VEG",
    description: "Steamed long grain basmati rice.",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVTng9pJz_v6gt6ewpc3EyBarG23-0mfB7LQ&s",
    add: false,
    category: { id: 8, name: "Sides" },
    dishType: "ACCOMPANIMENT",
    forChefit: true,
    forParty: true,
    id: 23,
    name: "Steamed Rice",
    ingredients: [
      { name: "Basmati Rice", quantity: "100 gm", type: "VEG" },
      { name: "Water", quantity: "200 ml", type: "VEG" },
      { name: "Salt", quantity: "to taste", type: "VEG" },
    ],
  },
];

export default dishes;
